const LOGIN = "LOGIN"
const LOGOUT = "LOGOUT"
const FETCHED_MEMBERS = "FETCHED_MEMBERS"
const CLEAR_MEMBERS = "CLEAR_MEMBERS"
const FETCHED_GROUPS = "FETCHED_GROUPS"
const CLEAR_GROUPS = "CLEAR_GROUPS"

export {LOGIN, LOGOUT, FETCHED_MEMBERS, CLEAR_MEMBERS, FETCHED_GROUPS, CLEAR_GROUPS}
